apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspector
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["/bin/sleep", "infinity"]  # Hält den Container am Laufen
    volumeMounts:
    - name: data-volume
      mountPath: /mnt/data  # Der Pfad, an dem die PVC im Container eingebunden wird
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: data-camunda-zeebe-0  # Der Name Ihrer PVC