apiVersion: batch/v1
kind: Job
metadata:
  name: zeebe-export-pause
spec:
  template:
    spec:
      containers:
      - name: pause-exporting
        image: curlimages/curl
        command: ["/bin/sh"]
        args:
        - -c
        - |
          curl -X POST "http://camunda-zeebe-gateway:9600/actuator/exporting/pause" \
            -H 'Content-Type: application/json' \
            -d '{}'
          echo "Exporting paused on camunda-zeebe-gateway."
      restartPolicy: Never